name: tidings_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.0
  provider: ^3.1.0
  custom_navigator: ^0.2.0
  cloud_firestore: ^0.12.9+4
  flutter_spinkit: ^4.1.2+1
  cupertino_icons: ^0.1.2
  flutter_datetime_picker: ^1.3.8
  flutter_datetime_formfield: ^0.1.2
  intl: ^0.16.1
  flutter_dialogflow: ^0.1.3
  url_launcher: ^5.5.0
  fluttertoast: ^7.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/google_plus_logo.png
    - assets/tidingschatbot-woughn-ef4239cde865.json
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-bold.ttf
          weight: 700

  
  